<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdd4bf289ced75046af9343c472006969
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'APP\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'APP\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdd4bf289ced75046af9343c472006969::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdd4bf289ced75046af9343c472006969::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitdd4bf289ced75046af9343c472006969::$classMap;

        }, null, ClassLoader::class);
    }
}
